### ISSUE TITLE
Some VB.Net programs crash the neon compiler (particularly when method return types are implicit)

### ISSUE THREAD

**Issue by djnicholson** [neo-project/neo-devpack-dotnet#197]
This compiles fine:

```
Imports Neo.SmartContract.Framework

Public Class SmartContract1 : Inherits SmartContract

    Public Shared Function Main()
        Main = SomeMethod()
    End Function

    Public Shared Function SomeMethod() As Boolean
       SomeMethod = True
    End Function

End Class
```

This compiles into MSIL but then crashes the neon compiler:

```
Imports Neo.SmartContract.Framework

Public Class SmartContract1 : Inherits SmartContract

    Public Shared Function Main()
        Main = SomeMethod()
    End Function

    Public Shared Function SomeMethod()
       SomeMethod = True
    End Function

End Class
```

Compiler output:
```
Microsoft (R) Build Engine version 16.4.0+e901037fe for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  Restore completed in 36.28 ms for /Users/david/neo-visual-tracker/sample-workspace/TestVB/TestVB.vbproj.
  TestVB -> /Users/david/neo-visual-tracker/sample-workspace/TestVB/bin/Debug/netstandard2.0/TestVB.dll
  Neo.Compiler.MSIL console app v2.6.0.0
EXEC : Convert error : System.Exception: error:System.Object TestVB.SmartContract1::Main()::IL_0006 Call System.Object System.Runtime.CompilerServices.RuntimeHelpers::GetObjectValue(System.Object) [/Users/david/neo-visual-tracker/sample-workspace/TestVB/TestVB.vbproj]
   ---> System.NullReferenceException: Object reference not set to an instance of an object.
     at Neo.Compiler.MSIL.OpCode.InitToken(Object _p) in d:\a\1\s\Neo.Compiler.MSIL\MSIL\ILModule.cs:line 795
     at Neo.Compiler.MSIL.ILMethod..ctor(ILType type, MethodDefinition method, ILogger logger) in d:\a\1\s\Neo.Compiler.MSIL\MSIL\ILModule.cs:line 256
     at Neo.Compiler.MSIL.ILType..ctor(ILModule module, TypeDefinition type, ILogger logger) in d:\a\1\s\Neo.Compiler.MSIL\MSIL\ILModule.cs:line 85
     at Neo.Compiler.MSIL.ModuleConverter.TryInsertMethod(NeoModule outModule, MethodDefinition method) in d:\a\1\s\Neo.Compiler.MSIL\MSIL\Conv_Multi.cs:line 1161
     at Neo.Compiler.MSIL.ModuleConverter._ConvertCall(OpCode src, NeoMethod to) in d:\a\1\s\Neo.Compiler.MSIL\MSIL\Conv_Multi.cs:line 776
     at Neo.Compiler.MSIL.ModuleConverter.ConvertCode(ILMethod method, OpCode src, NeoMethod to) in d:\a\1\s\Neo.Compiler.MSIL\MSIL\Converter.cs:line 834
     at Neo.Compiler.MSIL.ModuleConverter.ConvertMethod(ILMethod from, NeoMethod to) in d:\a\1\s\Neo.Compiler.MSIL\MSIL\Converter.cs:line 395
     --- End of inner exception stack trace ---
     at Neo.Compiler.MSIL.ModuleConverter.ConvertMethod(ILMethod from, NeoMethod to) in d:\a\1\s\Neo.Compiler.MSIL\MSIL\Converter.cs:line 399
     at Neo.Compiler.MSIL.ModuleConverter.Convert(ILModule _in, ConvOption option) in d:\a\1\s\Neo.Compiler.MSIL\MSIL\Converter.cs:line 136
     at Neo.Compiler.Program.Main(String[] args) in d:\a\1\s\Neo.Compiler.MSIL\Program.cs:line 191
/Users/david/neo-visual-tracker/sample-workspace/TestVB/Directory.Build.targets(8,5): error MSB3073: The command "neon TestVB.dll" exited with code 255. [/Users/david/neo-visual-tracker/sample-workspace/TestVB/TestVB.vbproj]
```

**Comment by shargon** [comment]
The problem is with this call `System.Runtime.CompilerServices.RuntimeHelpers::GetObjectValue`
@lightszero I think that this method make a copy if it's an struct, otherwise it return the object. Could you check it?

**Comment by lightszero** [comment]
ok，I'm not good at vb.net,I will study it and create some unittest.

**Comment by lightszero** [comment]
I found a problem, now it worked when code below 

```vb.net
Imports Neo


Public Class SmartContract2 : Inherits SmartContract.Framework.SmartContract

    Public Shared Function Main()
        Main = UnitTest_002()
    End Function

    Public Shared Function UnitTest_002() 'no return type here.
        Dim buffer = New Byte() {1, 2, 3, 4}
        UnitTest_002 = buffer(2)
    End Function

End Class
```

**Comment by shargon** [comment]
Please @djnicholson check it again, feel free to reopen it if you consider.
