### ISSUE TITLE
An Issue for stringArray in smart contract when compile

### ISSUE THREAD

**Issue by superboyiii** [neo-project/neo-devpack-dotnet#211]
Refer to https://github.com/neo-project/neo-devpack-dotnet/pull/187#discussion_r394673272.
`static readonly string[] SupportedStandards = new string[] { "NEP-5", "NEP-10" };` 
This kind of style can cause compilation error.
```
2>Find entrypoint:System.Object Template.NEP5.CSharp.NEP5::Main(System.String,System.Object[])
2>EXEC : Convert error : System.Exception: sth error
2>   at Neo.Compiler.MSIL.ModuleConverter.LinkCode(String main) in D:\Master-smoking\2020-03-20\neo-devpack-dotnet\src\Neo.Compiler.MSIL\MSIL\Converter.cs:line 359
2>   at Neo.Compiler.MSIL.ModuleConverter.Convert(ILModule _in, ConvOption option) in D:\Master-smoking\2020-03-20\neo-devpack-dotnet\src\Neo.Compiler.MSIL\MSIL\Converter.cs:line 200
2>   at Neo.Compiler.Program.Compile(Options options) in D:\Master-smoking\2020-03-20\neo-devpack-dotnet\src\Neo.Compiler.MSIL\Program.cs:line 159
2>D:\Master-smoking\2020-03-20\neo-devpack-dotnet\templates\Template.NEP5.CSharp\Template.NEP5.CSharp.csproj(12,5): error MSB3073: The command "neon -f "D:\Master-smoking\2020-03-20\neo-devpack-dotnet\templates\Template.NEP5.CSharp\bin\Debug\netstandard2.1\Template.NEP5.CSharp.dll" -o" exited with code -1.
2>Done building project "Template.NEP5.CSharp.csproj" -- FAILED.
```

**Comment by lightszero** [comment]
i will check that.
