### ISSUE TITLE
integer type in switch condition is not supported

### ISSUE THREAD

**Issue by cloud8little** [neo-project/neo-devpack-dotnet#292]
test cases:  #291 
```
 public static object Main(int b)
        {
            int a = 1;
            switch (b)
            {
                case 1:
                    a = 2;
                    break;
                case 2:
                    a = 3;
                    break;
                case 3:
                    a = 6;
                    break;
                default:
                    a = 0;
                    break;
            }
            return a;
        }
```
```
2020-06-12T07:20:37.6786545Z A total of 1 test files matched the specified pattern.
2020-06-12T07:20:43.9136391Z   X Test_SwitchInteger [60ms]
2020-06-12T07:20:43.9136927Z   Error Message:
2020-06-12T07:20:43.9137278Z    Test method Neo.Compiler.MSIL.UnitTests.UnitTest_Switch.Test_SwitchInteger threw exception: 
2020-06-12T07:20:43.9138983Z System.Exception: error:System.Object Neo.Compiler.MSIL.UnitTests.TestClasses.Contract_SwitchValid::Main(System.Int32)::IL_000A Switch  ---> System.Exception: need neo.VM update.
2020-06-12T07:20:43.9139372Z   Stack Trace:
2020-06-12T07:20:43.9140108Z       at Neo.Compiler.MSIL.ModuleConverter.ConvertCode(ILMethod method, OpCode src, NeoMethod to) in /home/runner/work/neo-devpack-dotnet/neo-devpack-dotnet/src/Neo.Compiler.MSIL/MSIL/Converter.cs:line 579
2020-06-12T07:20:43.9140860Z    at Neo.Compiler.MSIL.ModuleConverter.FillMethod(ILMethod from, NeoMethod to, Boolean withReturn) in /home/runner/work/neo-devpack-dotnet/neo-devpack-dotnet/src/Neo.Compiler.MSIL/MSIL/Converter.cs:line 280
2020-06-12T07:20:43.9141441Z --- End of inner exception stack trace ---
2020-06-12T07:20:43.9142129Z     at Neo.Compiler.MSIL.ModuleConverter.FillMethod(ILMethod from, NeoMethod to, Boolean withReturn) in /home/runner/work/neo-devpack-dotnet/neo-devpack-dotnet/src/Neo.Compiler.MSIL/MSIL/Converter.cs:line 284
2020-06-12T07:20:43.9142846Z    at Neo.Compiler.MSIL.ModuleConverter.ConvertMethod(ILMethod from, NeoMethod to) in /home/runner/work/neo-devpack-dotnet/neo-devpack-dotnet/src/Neo.Compiler.MSIL/MSIL/Converter.cs:line 300
2020-06-12T07:20:43.9143553Z    at Neo.Compiler.MSIL.ModuleConverter.Convert(ILModule _in, ConvOption option) in /home/runner/work/neo-devpack-dotnet/neo-devpack-dotnet/src/Neo.Compiler.MSIL/MSIL/Converter.cs:line 138
2020-06-12T07:20:43.9144321Z    at Neo.Compiler.MSIL.UnitTests.Utils.BuildScript.Build(Stream fs, Stream fspdb, Boolean optimizer) in /home/runner/work/neo-devpack-dotnet/neo-devpack-dotnet/tests/Neo.Compiler.MSIL.UnitTests/Utils/BuildScript.cs:line 53
2020-06-12T07:20:43.9145080Z    at Neo.Compiler.MSIL.UnitTests.Utils.NeonTestTool.BuildScript(String[] filenames, Boolean releaseMode, Boolean optimizer) in /home/runner/work/neo-devpack-dotnet/neo-devpack-dotnet/tests/Neo.Compiler.MSIL.UnitTests/Utils/NeonTestTool.cs:line 79
2020-06-12T07:20:43.9146149Z    at Neo.Compiler.MSIL.UnitTests.Utils.NeonTestTool.BuildScript(String filename, Boolean releaseMode, Boolean optimizer) in /home/runner/work/neo-devpack-dotnet/neo-devpack-dotnet/tests/Neo.Compiler.MSIL.UnitTests/Utils/NeonTestTool.cs:line 55
2020-06-12T07:20:43.9147297Z    at Neo.Compiler.MSIL.UnitTests.Utils.TestEngine.Build(String filename, Boolean releaseMode, Boolean optimizer) in /home/runner/work/neo-devpack-dotnet/neo-devpack-dotnet/tests/Neo.Compiler.MSIL.UnitTests/Utils/TestEngine.cs:line 53
2020-06-12T07:20:43.9148215Z    at Neo.Compiler.MSIL.UnitTests.Utils.TestEngine.AddEntryScript(String filename, Boolean releaseMode, Boolean optimizer) in /home/runner/work/neo-devpack-dotnet/neo-devpack-dotnet/tests/Neo.Compiler.MSIL.UnitTests/Utils/TestEngine.cs:line 73
2020-06-12T07:20:43.9148916Z    at Neo.Compiler.MSIL.UnitTests.UnitTest_Switch.Test_SwitchInteger() in /home/runner/work/neo-devpack-dotnet/neo-devpack-dotnet/tests/Neo.Compiler.MSIL.UnitTests/UnitTest_Switch.cs:line 78
```

**Comment by lightszero** [comment]
got it,will working on it.

**Comment by lightszero** [comment]
fix it in your ut pr

**Comment by ShawnYun** [comment]
we can close it via https://github.com/neo-project/neo-devpack-dotnet/pull/291
