### ISSUE TITLE
Template.NEP5.CSharp not building w/ Neo master

### ISSUE THREAD

**Issue by devhawk** [neo-project/neo-devpack-dotnet#368]
Updated local devpack repo to point to a local neo repo, both at master. running `dotnet build` in devpack repo yields this error

```
 Neo.Compiler.MSIL console app v3.0.0.0
EXEC : Convert error : System.Exception: error:System.Boolean Template.NEP5.CSharp.NEP5::Mint()::IL_0170 Callvirt System.Void System.Action`3<System.Byte[],System.Byte[],System.Numerics.BigInteger>::Invoke(!0,!1,!2) [C:\Users\harry\Source\neo\official\devpack\templates\Template.NEP5.CSharp\Template.NEP5.CSharp.csproj]
   ---> System.TypeInitializationException: The type initializer for 'Neo.SmartContract.ApplicationEngine' threw an exception.
   ---> System.Reflection.AmbiguousMatchException: Ambiguous match found.
     at System.RuntimeType.GetMethodImplCommon(String name, Int32 genericParameterCount, BindingFlags bindingAttr, Binder binder, CallingConventions callConv, Type[] types, ParameterModifier[] modifiers)
     at System.RuntimeType.GetMethodImpl(String name, BindingFlags bindingAttr, Binder binder, CallingConventions callConv, Type[] types, ParameterModifier[] modifiers)
     at System.Type.GetMethod(String name, BindingFlags bindingAttr)
     at Neo.SmartContract.ApplicationEngine.Register(String name, String handler, Int64 fixedPrice, CallFlags requiredCallFlags, Boolean allowCallback) in C:\Users\harry\Source\neo\official\core\src\neo\SmartContract\ApplicationEngine.cs:line 296
     at Neo.SmartContract.ApplicationEngine..cctor() in C:\Users\harry\Source\neo\official\core\src\neo\SmartContract\ApplicationEngine.Blockchain.cs:line 15
     --- End of inner exception stack trace ---
     at Neo.Compiler.MSIL.ModuleConverter.ConvertCall(OpCode src, NeoMethod to) in C:\Users\harry\Source\neo\official\devpack\src\Neo.Compiler.MSIL\MSIL\Conv_Multi.cs:line 901
     at Neo.Compiler.MSIL.ModuleConverter.ConvertCode(ILMethod method, OpCode src, NeoMethod to) in C:\Users\harry\Source\neo\official\devpack\src\Neo.Compiler.MSIL\MSIL\Converter.cs:line 793
     at Neo.Compiler.MSIL.ModuleConverter.FillMethod(ILMethod from, NeoMethod to, Boolean withReturn) in C:\Users\harry\Source\neo\official\devpack\src\Neo.Compiler.MSIL\MSIL\Converter.cs:line 265
     --- End of inner exception stack trace ---
     at Neo.Compiler.MSIL.ModuleConverter.FillMethod(ILMethod from, NeoMethod to, Boolean withReturn) in C:\Users\harry\Source\neo\official\devpack\src\Neo.Compiler.MSIL\MSIL\Converter.cs:line 269
     at Neo.Compiler.MSIL.ModuleConverter.ConvertMethod(ILMethod from, NeoMethod to) in C:\Users\harry\Source\neo\official\devpack\src\Neo.Compiler.MSIL\MSIL\Converter.cs:line 285
     at Neo.Compiler.MSIL.ModuleConverter.Convert(ILModule _in, ConvOption option) in C:\Users\harry\Source\neo\official\devpack\src\Neo.Compiler.MSIL\MSIL\Converter.cs:line 123
     at Neo.Compiler.Program.Compile(Options options, ILogger log) in C:\Users\harry\Source\neo\official\devpack\src\Neo.Compiler.MSIL\Program.cs:line 165
C:\Users\harry\Source\neo\official\devpack\templates\Template.NEP5.CSharp\Template.NEP5.CSharp.csproj(12,5): error MSB3073: The command "dotnet C:\Users\harry\Source\neo\official\devpack\src\Neo.Compiler.MSIL\bin\Debug\netcoreapp3.1\neon.dll -f "C:\Users\harry\Source\neo\official\devpack\templates\Template.NEP5.CSharp\bin\Debug\netstandard2.1\Template.NEP5.CSharp.dll" -o" exited with code -1.
```

**Comment by devhawk** [comment]
My bad, testing out something local and forgot to remove
