### ISSUE TITLE
Smart Contract templates do not compile correctly (master branch)

### ISSUE THREAD

**Issue by chenzhitong** [neo-project/neo-devpack-dotnet#397]
Smart Contract templates do not compile correctly
![image](https://user-images.githubusercontent.com/6295602/100302289-fe3e4c80-2fd4-11eb-85d8-1974ee30412a.png)

![image](https://user-images.githubusercontent.com/6295602/100302305-039b9700-2fd5-11eb-810f-60a9fd57b5b4.png)

```
Neo.Compiler.MSIL console app v3.0.0.0
Convert Error:System.NullReferenceException: Object reference not set to an instance of an object.
   at Neo.Compiler.MSIL.CctorSubVM.Parse(ILMethod from, NeoModule to) in D:\1Code\neo\neo-devpack-dotnet\src\Neo.Compiler.MSIL\MSIL\CctorSubVM.cs:line 173
   at Neo.Compiler.MSIL.ModuleConverter.Convert(ILModule _in, ConvOption option) in D:\1Code\neo\neo-devpack-dotnet\src\Neo.Compiler.MSIL\MSIL\Converter.cs:line 62
   at Neo.Compiler.Program.Compile(Options options, ILogger log) in D:\1Code\neo\neo-devpack-dotnet\src\Neo.Compiler.MSIL\Program.cs:line 165
```

**Comment by ProDog** [comment]
My tests are normal. Maybe the contract's pot?

```
PS D:\neo_code\neo-devpack-dotnet\src\Neo.Compiler.MSIL\bin\Debug\netcoreapp3.1> dotnet neon.dll -f .\Template.NEP5.CSharp.dll
Neo.Compiler.MSIL console app v3.0.0.0
Insert _initialize().
convert succ
gen abi succ
gen debug succ
write:Template.NEP5.CSharp.nef
write:Template.NEP5.CSharp.abi.json
write:Template.NEP5.CSharp.nefdbgnfo
write:Template.NEP5.CSharp.manifest.json
SUCC

PS D:\neo_code\neo-devpack-dotnet\src\Neo.Compiler.MSIL\bin\Debug\netcoreapp3.1> dotnet neon.dll
Neo.Compiler.MSIL 3.0.0-preview3
2015-2020 The Neo Project

ERROR(S):
  Required option 'f, file' is missing.

  -f, --file        Required. File for compile.

  -o, --optimize    Optimize.

  --help            Display this help screen.

  --version         Display version information.

PS D:\neo_code\neo-devpack-dotnet\src\Neo.Compiler.MSIL\bin\Debug\netcoreapp3.1>
```
