### ISSUE TITLE
neon 3.0.0-preview4 works on Windows but gives build error on Mac (not support opcode IL_000A Newobj System.Void System.DateTime::.ctor)

### ISSUE THREAD

**Issue by djnicholson** [neo-project/neo-devpack-dotnet#417]
I have a Windows and Mac machine; both have .NET Core 3.1.404 and both have neon installed globally:

```
# dotnet --version
3.1.404
# dotnet tool install -g neo.neon --version 3.0.0-preview4
You can invoke the tool using the following command: neon
Tool 'neo.neon' (version '3.0.0-preview4') was successfully installed.
# neon --version
Neo.Compiler.MSIL 3.0.0-preview4
```

I also have the same trivial contract code on each machine:

```
using System.ComponentModel;
using Neo.SmartContract.Framework;
namespace Foo
{
    [DisplayName("YourName.FooContract")]
    [ManifestExtra("Author", "Your name")]
    [ManifestExtra("Email", "your@address.invalid")]
    [ManifestExtra("Description", "Describe your contract...")]
    public class FooContract : SmartContract
    {
        public static bool HelloWorld()
        {
            return true;
        }
    }
}
```

The above code compiles to MSIL fine on Windows and Mac.  

On Windows, `neon -f FooContract.dll` works as expected. On Mac, I see the following:

```
EXEC : Convert error : System.Exception: not support opcode IL_000A Newobj System.Void System.DateTime::.ctor(System.Int64,System.DateTimeKind) in cctor. [/Users/david/github/@ngdseattle/neo3-visual-tracker/sample-workspaces/empty-workspace/Foo/FooContract.csproj]
     at Neo.Compiler.MSIL.CctorSubVM.Parse(ILMethod from, NeoModule to) in C:\Users\erik\source\repos\neo-project\neo-devpack-dotnet\src\Neo.Compiler.MSIL\MSIL\CctorSubVM.cs:line 43
     at Neo.Compiler.MSIL.ModuleConverter.Convert(ILModule _in, ConvOption option) in C:\Users\erik\source\repos\neo-project\neo-devpack-dotnet\src\Neo.Compiler.MSIL\MSIL\Converter.cs:line 52
     at Neo.Compiler.Program.Compile(Options options, ILogger log) in C:\Users\erik\source\repos\neo-project\neo-devpack-dotnet\src\Neo.Compiler.MSIL\Program.cs:line 164
```

**Comment by Tommo-L** [comment]
We'll fix it.

**Comment by gsmachado** [comment]
+1

**Comment by erikzhang** [comment]
Is it fixed?

**Comment by djnicholson** [comment]
This no longer repros on my Mac with neon 3.0.0-rc1
