### ISSUE TITLE
Slot initialized error when change local variables in contract and return type is void

### ISSUE THREAD

**Issue by cloud8little** [neo-project/neo-devpack-dotnet#419]
contract like this(change a's value and put the value back to a ):

```cs
        public static void Testvoid(int a, int b)
        {
            a = a + 2;
        }
```

```
optimization ratio = 71.296295%
op:[0045]INITSLOT
op:[0048]LDARG0
op:[0049]PUSH2
op:[004A]ADD
op:[004B]STLOC0
System.InvalidOperationException: Slot has not been initialized.
   at Neo.VM.ExecutionEngine.ExecuteStoreToSlot(Slot slot, Int32 index) in D:\Github\neo-vm\src\neo-vm\ExecutionEngine.cs:line 1309
   at Neo.VM.ExecutionEngine.ExecuteInstruction() in D:\Github\neo-vm\src\neo-vm\ExecutionEngine.cs:line 566
   at Neo.VM.ExecutionEngine.ExecuteNext() in D:\Github\neo-vm\src\neo-vm\ExecutionEngine.cs:line 1294
```

or 

```cs
        public static void testvoidinputstring(string a)
        {
            a = a + "abc";
        }
```

**Comment by erikzhang** [comment]
`op:[004B]STLOC0` should be `op:[004B]STARG0`.

**Comment by cloud8little** [comment]
> `op:[004B]STLOC0` should be `op:[004B]STARG0`.

why it did not show error when return type is not void?
