### ISSUE TITLE
Error when compiling example with nccs

### ISSUE THREAD

**Issue by vncoelho** [neo-project/neo-devpack-dotnet#565]
we are still setting up NeoCompiler Eco for the new nccs compiler.

We got the following error using this template:

```cs
using Neo;
using Neo.SmartContract;
using Neo.SmartContract.Framework;
using Neo.SmartContract.Framework.Native;
using Neo.SmartContract.Framework.Services;
using System;
using System.Numerics;

namespace HelloWorldDemo
{
    [ManifestExtra("Author", "Neo")]
    [ManifestExtra("Email", "dev@neo.org")]
    [ManifestExtra("Description", "This is a contract example")]
    public class Contract1 : SmartContract
    {
        //TODO: Replace it with your own address.
        [InitialValue("NiNmXL8FjEUEs1nfX9uHFBNaenxDHJtmuB", ContractParameterType.Hash160)]
        static readonly UInt160 Owner = default;

        private static bool IsOwner() => Runtime.CheckWitness(Owner);

        // When this contract address is included in the transaction signature,
        // this method will be triggered as a VerificationTrigger to verify that the signature is correct.
        // For example, this method needs to be called when withdrawing token from the contract.
        public static bool Verify() => IsOwner();

        // TODO: Replace it with your methods.
        public static string MyMethod()
        {
            return Storage.Get(Storage.CurrentContext, "Hello");
        }

        public static void _deploy(object data, bool update)
        {
            if (update) return;

            // It will be executed during deploy
            Storage.Put(Storage.CurrentContext, "Hello", "World");
        }

        public static void Update(ByteString nefFile, string manifest)
        {
            if (!IsOwner()) throw new Exception("No authorization.");
            ContractManagement.Update(nefFile, manifest, null);
        }

        public static void Destroy()
        {
            if (!IsOwner()) throw new Exception("No authorization.");
            ContractManagement.Destroy();
        }
    }
}
```

```cs
Neo compiler version (latest): 
Git log: 
eb828f14af7a6814762fe266afcfb812c46b6322
Smart Contract Framework version (latest): 
Building...

Microsoft (R) Build Engine version 16.8.0+126527ff1 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore...
  Restored /neo-devpack-dotnet/templates/Template.CSharpNeoCompiler/Template.CSharpNeoCompiler.csproj (in 102 ms).
  1 of 2 projects are up-to-date for restore.
  Neo.SmartContract.Framework -> /neo-devpack-dotnet/src/Neo.SmartContract.Framework/bin/Debug/net5.0/Neo.SmartContract.Framework.dll
  Template.CSharpNeoCompiler -> /neo-devpack-dotnet/templates/Template.CSharpNeoCompiler/bin/Debug/net5.0/Template.CSharpNeoCompiler.dll
  Start NeoContract converter, Source File: /neo-devpack-dotnet/templates/Template.CSharpNeoCompiler/bin/Debug/net5.0/Template.CSharpNeoCompiler.dll - Project Path /neo-devpack-dotnet/templates/Template.CSharpNeoCompiler/Template.CSharpNeoCompiler.csproj
    Determining projects to restore...
    All projects are up-to-date for restore.
  Unhandled exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
   ---> System.NullReferenceException: Object reference not set to an instance of an object.
     at Neo.Compiler.CompilationContext.CompileProject(String csproj, Options options) in /neo-devpack-dotnet/src/Neo.Compiler.CSharp/CompilationContext.cs:line 160
     at Neo.Compiler.Program.ProcessCsproj(Options options, String path) in /neo-devpack-dotnet/src/Neo.Compiler.CSharp/Program.cs:line 82
     at Neo.Compiler.Program.Handle(Options options, String[] paths) in /neo-devpack-dotnet/src/Neo.Compiler.CSharp/Program.cs:line 42
     --- End of inner exception stack trace ---
     at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
     at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
     at System.Delegate.DynamicInvokeImpl(Object[] args)
     at System.Delegate.DynamicInvoke(Object[] args)
     at System.CommandLine.Invocation.ModelBindingCommandHandler.InvokeAsync(InvocationContext context)
     at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
  --- End of stack trace from previous location ---
     at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseParseErrorReporting>b__21_0>d.MoveNext()
  --- End of stack trace from previous location ---
     at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass16_0.<<UseHelp>b__0>d.MoveNext()
  --- End of stack trace from previous location ---
     at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass25_0.<<UseVersionOption>b__0>d.MoveNext()
  --- End of stack trace from previous location ---
     at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass23_0.<<UseTypoCorrections>b__0>d.MoveNext()
  --- End of stack trace from previous location ---
     at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__22_0>d.MoveNext()
  --- End of stack trace from previous location ---
     at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseParseDirective>b__20_0>d.MoveNext()
  --- End of stack trace from previous location ---
     at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseDebugDirective>b__11_0>d.MoveNext()
  --- End of stack trace from previous location ---
     at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<RegisterWithDotnetSuggest>b__10_0>d.MoveNext()
  --- End of stack trace from previous location ---
     at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass14_0.<<UseExceptionHandler>b__0>d.MoveNext()
/neo-devpack-dotnet/templates/Template.CSharpNeoCompiler/Template.CSharpNeoCompiler.csproj(14,5): error MSB3073: The command "/neo-devpack-dotnet/src/Neo.Compiler.CSharp/bin/Debug/net5.0/nccs "/neo-devpack-dotnet/templates/Template.CSharpNeoCompiler/Template.CSharpNeoCompiler.csproj" " exited with code 1.

Build FAILED.

/neo-devpack-dotnet/templates/Template.CSharpNeoCompiler/Template.CSharpNeoCompiler.csproj(14,5): error MSB3073: The command "/neo-devpack-dotnet/src/Neo.Compiler.CSharp/bin/Debug/net5.0/nccs "/neo-devpack-dotnet/templates/Template.CSharpNeoCompiler/Template.CSharpNeoCompiler.csproj" " exited with code 1.
    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:04.82
```

**Comment by erikzhang** [comment]
> Source File: /neo-devpack-dotnet/templates/Template.CSharpNeoCompiler/bin/Debug/net5.0/Template.CSharpNeoCompiler.dll

Why the source file is a .dll?

**Comment by vncoelho** [comment]
I do not know, it was given as a generic folder:

```cs
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net5.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Neo.SmartContract.Framework\Neo.SmartContract.Framework.csproj" />
  </ItemGroup>

  <Target Name="PostBuild" AfterTargets="PostBuildEvent">
    <Message Text="Start NeoContract converter, Source File: $(TargetPath) - Project Path $(ProjectPath)" Importance="high">
    </Message>
    <Exec Command="/neo-devpack-dotnet/src/Neo.Compiler.CSharp/bin/$(ConfigurationName)/net5.0/nccs &quot;$(ProjectPath)&quot;" />
  </Target>
  
</Project>
```


```cs
(cd /neo-devpack-dotnet/ && dotnet build ./templates/Template.CSharpNeoCompiler/Template.CSharpNeoCompiler.csproj) >> /tmp/output.txt
```

**Comment by vncoelho** [comment]
Using the last branch `ProjectReference`, the problem was solved.
