### ISSUE TITLE
Interface field causes nccs to crash

### ISSUE THREAD

**Issue by devhawk** [neo-project/neo-devpack-dotnet#567]
Contract:
``` csharp
using Neo;
using Neo.SmartContract;
using Neo.SmartContract.Framework;
using Neo.SmartContract.Framework.Native;
using Neo.SmartContract.Framework.Services;
using System;
using System.Numerics;

namespace NeoContract1
{
	
    [ManifestExtra("Author", "Neo")]
    [ManifestExtra("Email", "dev@neo.org")]
    [ManifestExtra("Description", "This is a contract example")]
    public class Contract1 : SmartContract
    {
        AccountStorage accountStorage = new();

        IStorageMap<UInt160, BigInteger> Accounts => accountStorage;

        public void TransferAll(UInt160 from, UInt160 to)
        {
            Accounts[to] = Accounts[from] + Accounts[to];
            Accounts[from] = 0;
        }

        public void SetValue(UInt160 addr, BigInteger amount)
        {
            Accounts[addr] = amount;
        }

        public BigInteger GetValue(UInt160 addr)
        {
            return Accounts[addr];
        }
    }

    interface IStorageMap<TKey, TValue>
    {
        TValue this[TKey account] { get; set; }
    }

    class AccountStorage : IStorageMap<UInt160, BigInteger>
    {
        readonly StorageMap map;

        public AccountStorage()
        {
            map = new StorageMap(Storage.CurrentContext, nameof(AccountStorage));
        }

        public BigInteger this[UInt160 account]
        {
            get => (BigInteger)map.Get(account);
            set => map.Put(account, value);
        }
    }
}
```

Output:
``` shell
Unhandled exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Neo.Compiler.Helper.GetAllMembersInternal(ITypeSymbol type)+MoveNext() in C:\Users\harry\Source\neo\official\3neo-monorepo\devpack\src\Neo.Compiler.CSharp\Helper.cs:line 120
   at Neo.Compiler.Helper.GetAllMembersInternal(ITypeSymbol type)+MoveNext() in C:\Users\harry\Source\neo\official\3neo-monorepo\devpack\src\Neo.Compiler.CSharp\Helper.cs:line 123
   at System.Collections.Generic.LargeArrayBuilder`1.AddRange(IEnumerable`1 items)
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Neo.Compiler.Helper.GetAllMembers(ITypeSymbol type) in C:\Users\harry\Source\neo\official\3neo-monorepo\devpack\src\Neo.Compiler.CSharp\Helper.cs:line 115
   at Neo.Compiler.MethodConvert.CallVirtual(IMethodSymbol symbol) in C:\Users\harry\Source\neo\official\3neo-monorepo\devpack\src\Neo.Compiler.CSharp\MethodConvert.cs:line 4220
   at Neo.Compiler.MethodConvert.Call(SemanticModel model, IMethodSymbol symbol, ExpressionSyntax instanceExpression, SyntaxNode[] arguments) in C:\Users\harry\Source\neo\official\3neo-monorepo\devpack\src\Neo.Compiler.CSharp\MethodConvert.cs:line 3674
   at Neo.Compiler.MethodConvert.ConvertElementAccessExpression(SemanticModel model, ElementAccessExpressionSyntax expression) in C:\Users\harry\Source\neo\official\3neo-monorepo\devpack\src\Neo.Compiler.CSharp\MethodConvert.cs:line 2348
   at Neo.Compiler.MethodConvert.ConvertExpression(SemanticModel model, ExpressionSyntax syntax) in C:\Users\harry\Source\neo\official\3neo-monorepo\devpack\src\Neo.Compiler.CSharp\MethodConvert.cs:line 1131
   at Neo.Compiler.MethodConvert.ConvertBinaryExpression(SemanticModel model, BinaryExpressionSyntax expression) in C:\Users\harry\Source\neo\official\3neo-monorepo\devpack\src\Neo.Compiler.CSharp\MethodConvert.cs:line 1996
   at Neo.Compiler.MethodConvert.ConvertExpression(SemanticModel model, ExpressionSyntax syntax) in C:\Users\harry\Source\neo\official\3neo-monorepo\devpack\src\Neo.Compiler.CSharp\MethodConvert.cs:line 1119
   at Neo.Compiler.MethodConvert.ConvertSimpleAssignmentExpression(SemanticModel model, AssignmentExpressionSyntax expression) in C:\Users\harry\Source\neo\official\3neo-monorepo\devpack\src\Neo.Compiler.CSharp\MethodConvert.cs:line 1271
   at Neo.Compiler.MethodConvert.ConvertAssignmentExpression(SemanticModel model, AssignmentExpressionSyntax expression) in C:\Users\harry\Source\neo\official\3neo-monorepo\devpack\src\Neo.Compiler.CSharp\MethodConvert.cs:line 1258
   at Neo.Compiler.MethodConvert.ConvertExpression(SemanticModel model, ExpressionSyntax syntax) in C:\Users\harry\Source\neo\official\3neo-monorepo\devpack\src\Neo.Compiler.CSharp\MethodConvert.cs:line 1113
   at Neo.Compiler.MethodConvert.ConvertExpressionStatement(SemanticModel model, ExpressionStatementSyntax syntax) in C:\Users\harry\Source\neo\official\3neo-monorepo\devpack\src\Neo.Compiler.CSharp\MethodConvert.cs:line 558
   at Neo.Compiler.MethodConvert.ConvertStatement(SemanticModel model, StatementSyntax statement) in C:\Users\harry\Source\neo\official\3neo-monorepo\devpack\src\Neo.Compiler.CSharp\MethodConvert.cs:line 453
   at Neo.Compiler.MethodConvert.ConvertBlockStatement(SemanticModel model, BlockSyntax syntax) in C:\Users\harry\Source\neo\official\3neo-monorepo\devpack\src\Neo.Compiler.CSharp\MethodConvert.cs:line 504
   at Neo.Compiler.MethodConvert.ConvertStatement(SemanticModel model, StatementSyntax statement) in C:\Users\harry\Source\neo\official\3neo-monorepo\devpack\src\Neo.Compiler.CSharp\MethodConvert.cs:line 438
   at Neo.Compiler.MethodConvert.ConvertSource(SemanticModel model) in C:\Users\harry\Source\neo\official\3neo-monorepo\devpack\src\Neo.Compiler.CSharp\MethodConvert.cs:line 425
   at Neo.Compiler.MethodConvert.Convert(SemanticModel model) in C:\Users\harry\Source\neo\official\3neo-monorepo\devpack\src\Neo.Compiler.CSharp\MethodConvert.cs:line 131
   at Neo.Compiler.CompilationContext.ConvertMethod(SemanticModel model, IMethodSymbol symbol) in C:\Users\harry\Source\neo\official\3neo-monorepo\devpack\src\Neo.Compiler.CSharp\CompilationContext.cs:line 402
   at Neo.Compiler.CompilationContext.ProcessMethod(SemanticModel model, IMethodSymbol symbol, Boolean export) in C:\Users\harry\Source\neo\official\3neo-monorepo\devpack\src\Neo.Compiler.CSharp\CompilationContext.cs:line 382
   at Neo.Compiler.CompilationContext.ProcessClass(SemanticModel model, INamedTypeSymbol symbol) in C:\Users\harry\Source\neo\official\3neo-monorepo\devpack\src\Neo.Compiler.CSharp\CompilationContext.cs:line 349
   at Neo.Compiler.CompilationContext.ProcessMemberDeclaration(SemanticModel model, MemberDeclarationSyntax syntax) in C:\Users\harry\Source\neo\official\3neo-monorepo\devpack\src\Neo.Compiler.CSharp\CompilationContext.cs:line 306
   at Neo.Compiler.CompilationContext.ProcessMemberDeclaration(SemanticModel model, MemberDeclarationSyntax syntax) in C:\Users\harry\Source\neo\official\3neo-monorepo\devpack\src\Neo.Compiler.CSharp\CompilationContext.cs:line 303
   at Neo.Compiler.CompilationContext.ProcessCompilationUnit(SemanticModel model, CompilationUnitSyntax syntax) in C:\Users\harry\Source\neo\official\3neo-monorepo\devpack\src\Neo.Compiler.CSharp\CompilationContext.cs:line 294
   at Neo.Compiler.CompilationContext.Compile() in C:\Users\harry\Source\neo\official\3neo-monorepo\devpack\src\Neo.Compiler.CSharp\CompilationContext.cs:line 98
   at Neo.Compiler.CompilationContext.Compile(IEnumerable`1 sourceFiles, IEnumerable`1 references, Options options) in C:\Users\harry\Source\neo\official\3neo-monorepo\devpack\src\Neo.Compiler.CSharp\CompilationContext.cs:line 126
   at Neo.Compiler.CompilationContext.CompileSources(String[] sourceFiles, Options options) in C:\Users\harry\Source\neo\official\3neo-monorepo\devpack\src\Neo.Compiler.CSharp\CompilationContext.cs:line 134
   at Neo.Compiler.Program.ProcessSources(Options options, String folder, String[] sourceFiles) in C:\Users\harry\Source\neo\official\3neo-monorepo\devpack\src\Neo.Compiler.CSharp\Program.cs:line 87
   at Neo.Compiler.Program.Handle(Options options, String[] paths) in C:\Users\harry\Source\neo\official\3neo-monorepo\devpack\src\Neo.Compiler.CSharp\Program.cs:line 57
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at System.Delegate.DynamicInvoke(Object[] args)
   at System.CommandLine.Invocation.ModelBindingCommandHandler.InvokeAsync(InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseParseErrorReporting>b__21_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass16_0.<<UseHelp>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass25_0.<<UseVersionOption>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass23_0.<<UseTypoCorrections>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__22_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseParseDirective>b__20_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseDebugDirective>b__11_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<RegisterWithDotnetSuggest>b__10_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass14_0.<<UseExceptionHandler>b__0>d.MoveNext()
```

**Comment by erikzhang** [comment]
We currently have no plans to support interfaces.

**Comment by devhawk** [comment]
> We currently have no plans to support interfaces.

nccs should report that as an nccs specific diagnostic error, not throw an exception and crash
