### ISSUE TITLE
Running nccs at master gives Unhandled Exception

### ISSUE THREAD

**Issue by devhawk** [neo-project/neo-devpack-dotnet#721]
Unhandled exception: System.ArgumentException: The SetHandler call for command 'nccs' is missing an Argument or Option for the parameter at position 0. Did you mean to pass one of these?

   at System.CommandLine.Handler.GetValueForHandlerParameter[T](IValueDescriptor[] symbols, Int32& index, InvocationContext context)
   at System.CommandLine.Handler.<>c__DisplayClass4_0`4.<SetHandler>b__0(InvocationContext context)
   at System.CommandLine.Invocation.AnonymousCommandHandler.<>c__DisplayClass2_0.<.ctor>g__Handle|0(InvocationContext context)
   at System.CommandLine.Invocation.AnonymousCommandHandler.InvokeAsync(InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass18_0.<<UseParseErrorReporting>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass13_0.<<UseHelp>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass22_0.<<UseVersionOption>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass20_0.<<UseTypoCorrections>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__19_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass17_0.<<UseParseDirective>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<RegisterWithDotnetSuggest>b__6_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass9_0.<<UseExceptionHandler>b__0>d.MoveNext()

**Comment by devhawk** [comment]
Appears to be caused by the move to System.CommandLine Version 2.0.0-beta3 and the line 

``` cs
            rootCommand.SetHandler<RootCommand, Options, string[], InvocationContext>(Handle);
```

**Comment by devhawk** [comment]
@shargon @erikzhang this appears to be from #713

**Comment by devhawk** [comment]
Yes, reverting the command line package, the SetHandler call and the Handle method code to the previous commit seems to solve the issue

**Comment by Liaojinghui** [comment]
This either be a bug or the new version does not support `string[]`. Suggest rollback `System.CommandLine`  @shargon

**Comment by shargon** [comment]
If use `IEnumerable<string>` it works?

**Comment by Liaojinghui** [comment]
Nope

**Comment by erikzhang** [comment]
Revert? But sooner or later we will have to upgrade.

**Comment by shargon** [comment]
Please check https://github.com/neo-project/neo-devpack-dotnet/pull/724
