### ISSUE TITLE
[Bug][Neo.Compiler.CSharp] compiler build error when running nccs with empty strings

### ISSUE THREAD

**Issue by cschuchardt88** [neo-project/neo-devpack-dotnet#778]
```
Rebuild started...
1>------ Rebuild All started: Project: CallHelloWorld, Configuration: Debug Any CPU ------
Restored D:\Crypto\Projects\Neo-Network\TestContracts\CallHelloWorld\CallHelloWorld.csproj (in 4 ms).
Restored D:\Crypto\Projects\Neo-Network\TestContracts\HelloWorld\HelloWorld.csproj (in 4 ms).
1>D:\Crypto\Projects\Neo-Network\TestContracts\CallHelloWorld\HelloWorldContract.cs(12,45,12,48): warning CS0626: Method, operator, or accessor 'HelloWorldContract.Hash.get' is marked external and has no attributes on it. Consider adding a DllImport attribute to specify the external implementation.
1>D:\Crypto\Projects\Neo-Network\TestContracts\CallHelloWorld\HelloWorldContract.cs(14,37,14,45): warning CS0626: Method, operator, or accessor 'HelloWorldContract.SayHello()' is marked external and has no attributes on it. Consider adding a DllImport attribute to specify the external implementation.
1>CallHelloWorld -> D:\Crypto\Projects\Neo-Network\TestContracts\CallHelloWorld\bin\Debug\net7.0\CallHelloWorld.dll
1>  Determining projects to restore...
1>  All projects are up-to-date for restore.
1>Unhandled exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
1> ---> System.FormatException: One of the identified items was in an invalid format.
1>   at Neo.UInt160.Parse(String value)
1>   at Neo.Compiler.MethodConvert.ConvertExtern() in /home/runner/work/neo-devpack-dotnet/neo-devpack-dotnet/src/Neo.Compiler.CSharp/MethodConvert.cs:line 340
1>   at Neo.Compiler.MethodConvert.Convert(SemanticModel model) in /home/runner/work/neo-devpack-dotnet/neo-devpack-dotnet/src/Neo.Compiler.CSharp/MethodConvert.cs:line 139
1>   at Neo.Compiler.CompilationContext.ConvertMethod(SemanticModel model, IMethodSymbol symbol) in /home/runner/work/neo-devpack-dotnet/neo-devpack-dotnet/src/Neo.Compiler.CSharp/CompilationContext.cs:line 522
1>   at Neo.Compiler.MethodConvert.Call(SemanticModel model, IMethodSymbol symbol, ExpressionSyntax instanceExpression, SyntaxNode[] arguments) in /home/runner/work/neo-devpack-dotnet/neo-devpack-dotnet/src/Neo.Compiler.CSharp/MethodConvert.cs:line 3733
1>   at Neo.Compiler.MethodConvert.ConvertMethodInvocationExpression(SemanticModel model, IMethodSymbol symbol, ExpressionSyntax expression, ArgumentSyntax[] arguments) in /home/runner/work/neo-devpack-dotnet/neo-devpack-dotnet/src/Neo.Compiler.CSharp/MethodConvert.cs:line 2650
1>   at Neo.Compiler.MethodConvert.ConvertInvocationExpression(SemanticModel model, InvocationExpressionSyntax expression) in /home/runner/work/neo-devpack-dotnet/neo-devpack-dotnet/src/Neo.Compiler.CSharp/MethodConvert.cs:line 2620
1>   at Neo.Compiler.MethodConvert.ConvertExpression(SemanticModel model, ExpressionSyntax syntax) in /home/runner/work/neo-devpack-dotnet/neo-devpack-dotnet/src/Neo.Compiler.CSharp/MethodConvert.cs:line 1255
1>   at Neo.Compiler.MethodConvert.ConvertSource(SemanticModel model) in /home/runner/work/neo-devpack-dotnet/neo-devpack-dotnet/src/Neo.Compiler.CSharp/MethodConvert.cs:line 508
1>   at Neo.Compiler.MethodConvert.Convert(SemanticModel model) in /home/runner/work/neo-devpack-dotnet/neo-devpack-dotnet/src/Neo.Compiler.CSharp/MethodConvert.cs:line 161
1>   at Neo.Compiler.CompilationContext.ConvertMethod(SemanticModel model, IMethodSymbol symbol) in /home/runner/work/neo-devpack-dotnet/neo-devpack-dotnet/src/Neo.Compiler.CSharp/CompilationContext.cs:line 522
1>   at Neo.Compiler.CompilationContext.ProcessMethod(SemanticModel model, IMethodSymbol symbol, Boolean export) in /home/runner/work/neo-devpack-dotnet/neo-devpack-dotnet/src/Neo.Compiler.CSharp/CompilationContext.cs:line 502
1>   at Neo.Compiler.CompilationContext.ProcessClass(SemanticModel model, INamedTypeSymbol symbol) in /home/runner/work/neo-devpack-dotnet/neo-devpack-dotnet/src/Neo.Compiler.CSharp/CompilationContext.cs:line 460
1>   at Neo.Compiler.CompilationContext.ProcessMemberDeclaration(HashSet`1 processed, SemanticModel model, MemberDeclarationSyntax syntax) in /home/runner/work/neo-devpack-dotnet/neo-devpack-dotnet/src/Neo.Compiler.CSharp/CompilationContext.cs:line 407
1>   at Neo.Compiler.CompilationContext.ProcessMemberDeclaration(HashSet`1 processed, SemanticModel model, MemberDeclarationSyntax syntax) in /home/runner/work/neo-devpack-dotnet/neo-devpack-dotnet/src/Neo.Compiler.CSharp/CompilationContext.cs:line 403
1>   at Neo.Compiler.CompilationContext.ProcessCompilationUnit(HashSet`1 processed, SemanticModel model, CompilationUnitSyntax syntax) in /home/runner/work/neo-devpack-dotnet/neo-devpack-dotnet/src/Neo.Compiler.CSharp/CompilationContext.cs:line 394
1>   at Neo.Compiler.CompilationContext.Compile() in /home/runner/work/neo-devpack-dotnet/neo-devpack-dotnet/src/Neo.Compiler.CSharp/CompilationContext.cs:line 128
1>   at Neo.Compiler.CompilationContext.CompileProject(String csproj, Options options) in /home/runner/work/neo-devpack-dotnet/neo-devpack-dotnet/src/Neo.Compiler.CSharp/CompilationContext.cs:line 249
1>   at Neo.Compiler.Program.ProcessCsproj(Options options, String path) in /home/runner/work/neo-devpack-dotnet/neo-devpack-dotnet/src/Neo.Compiler.CSharp/Program.cs:line 110
1>   at Neo.Compiler.Program.Handle(RootCommand command, Options options, String[] paths, InvocationContext context) in /home/runner/work/neo-devpack-dotnet/neo-devpack-dotnet/src/Neo.Compiler.CSharp/Program.cs:line 45
1>   --- End of inner exception stack trace ---
1>   at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
1>   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
1>   at System.Delegate.DynamicInvokeImpl(Object[] args)
1>   at System.Delegate.DynamicInvoke(Object[] args)
1>   at System.CommandLine.NamingConventionBinder.ModelBindingCommandHandler.InvokeAsync(InvocationContext context)
1>   at System.CommandLine.NamingConventionBinder.ModelBindingCommandHandler.Invoke(InvocationContext context)
1>   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
1>--- End of stack trace from previous location ---
1>   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass17_0.<<UseParseErrorReporting>b__0>d.MoveNext()
1>--- End of stack trace from previous location ---
1>   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass12_0.<<UseHelp>b__0>d.MoveNext()
1>--- End of stack trace from previous location ---
1>   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass22_0.<<UseVersionOption>b__0>d.MoveNext()
1>--- End of stack trace from previous location ---
1>   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass19_0.<<UseTypoCorrections>b__0>d.MoveNext()
1>--- End of stack trace from previous location ---
1>   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__18_0>d.MoveNext()
1>--- End of stack trace from previous location ---
1>   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass16_0.<<UseParseDirective>b__0>d.MoveNext()
1>--- End of stack trace from previous location ---
1>   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<RegisterWithDotnetSuggest>b__5_0>d.MoveNext()
1>--- End of stack trace from previous location ---
1>   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass8_0.<<UseExceptionHandler>b__0>d.MoveNext()
1>D:\Crypto\Projects\Neo-Network\TestContracts\CallHelloWorld\CallHelloWorld.csproj(15,5): error MSB3073: The command "nccs "D:\Crypto\Projects\Neo-Network\TestContracts\CallHelloWorld\CallHelloWorld.csproj" --base-name CallHelloWorld --debug --assembly" exited with code 1.
1>Done building project "CallHelloWorld.csproj" -- FAILED.
========== Rebuild All: 0 succeeded, 1 failed, 0 skipped ==========
========== Rebuild started at 3:45 AM and took 04.874 seconds ==========
```

**Caused By Passing Empty String**
```csharp
[Contract("")]
```

```csharp
using Neo;
using Neo.SmartContract.Framework.Attributes;


namespace CallHelloWorld
{
    [Contract("")] // String.Empty causes nccs to crash
    public class HelloWorldContract
    {
        [ContractHash]
        public static extern UInt160 Hash { get; }

        public static extern string SayHello();
    }
}
```

**Comment by shargon** [comment]
It's an invalid format
