### ISSUE TITLE
neon can't compile netstandard2.0 assemblies

### ISSUE THREAD

**Issue by devhawk** [neo-project/neo-devpack-dotnet#78]
HelloWorld sample contract from neo-project/examples repo targets .NET Framework v4.6.2. I modified the project file to generate a netstandard2.0 dll and I got the following error results on the console

```
PS> dotnet build
Microsoft (R) Build Engine version 16.2.32702+c4012a063 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  Restore completed in 147.45 ms for C:\Users\harry\Source\neo\official\examples\csharp\HelloWorld\HelloWorld.csproj.
  HelloWorld -> C:\Users\harry\Source\neo\official\examples\csharp\HelloWorld\bin\Debug\netstandard2.0\HelloWorld.dll
  Neo.Compiler.MSIL console app v2.4.1.0
EXEC : Convert error : System.Exception: error:System.Boolean Neo.SmartContract.HelloWorld::Main(System.String,System.Object[])::IL_000B Call System.Void Neo.SmartContract.Framework.Services.Neo.Storage::Put(System.String,System.String) ---> System.NullReferenceException: Object reference not set to an instance of an object. [C:\Users\harry\Source\neo\official\examples\csharp\HelloWorld\HelloWorld.csproj]
     at Neo.Compiler.MSIL.ModuleConverter.TryInsertMethod(NeoModule outModule, MethodDefinition method) in C:\Users\harry\Source\neo\official\devpack-dotnet_master-3.x\src\Neo.Compiler.MSIL\MSIL\Conv_Multi.cs:line 967
     at Neo.Compiler.MSIL.ModuleConverter._ConvertCall(OpCode src, NeoMethod to) in C:\Users\harry\Source\neo\official\devpack-dotnet_master-3.x\src\Neo.Compiler.MSIL\MSIL\Conv_Multi.cs:line 795
     at Neo.Compiler.MSIL.ModuleConverter.ConvertCode(ILMethod method, OpCode src, NeoMethod to) in C:\Users\harry\Source\neo\official\devpack-dotnet_master-3.x\src\Neo.Compiler.MSIL\MSIL\Converter.cs:line 884
     at Neo.Compiler.MSIL.ModuleConverter.ConvertMethod(ILMethod from, NeoMethod to) in C:\Users\harry\Source\neo\official\devpack-dotnet_master-3.x\src\Neo.Compiler.MSIL\MSIL\Converter.cs:line 454
     --- End of inner exception stack trace ---
     at Neo.Compiler.MSIL.ModuleConverter.ConvertMethod(ILMethod from, NeoMethod to) in C:\Users\harry\Source\neo\official\devpack-dotnet_master-3.x\src\Neo.Compiler.MSIL\MSIL\Converter.cs:line 458
     at Neo.Compiler.MSIL.ModuleConverter.Convert(ILModule _in, ConvOption option) in C:\Users\harry\Source\neo\official\devpack-dotnet_master-3.x\src\Neo.Compiler.MSIL\MSIL\Converter.cs:line 197
     at Neo.Compiler.Program.Main(String[] args) in C:\Users\harry\Source\neo\official\devpack-dotnet_master-3.x\src\Neo.Compiler.MSIL\Program.cs:line 88
C:\Users\harry\Source\neo\official\examples\csharp\Directory.Build.targets(4,5): error MSB3073: The command "dotnet C:\Users\harry\Source\neo\official\devpack-dotnet_master-3.x\src\Neo.Compiler.MSIL\bin\Debug\netcoreapp2.0\publish\neon.dll HelloWorld.dll" exited with code -1. [C:\Users\harry\Source\neo\official\examples\csharp\HelloWorld\HelloWorld.csproj]

Build FAILED.

EXEC : Convert error : System.Exception: error:System.Boolean Neo.SmartContract.HelloWorld::Main(System.String,System.Object[])::IL_000B Call System.Void Neo.SmartContract.Framework.Services.Neo.Storage::Put(System.String,System.String) ---> System.NullReferenceException: Object reference not set to an instance of an object. [C:\Users\harry\Source\neo\official\examples\csharp\HelloWorld\HelloWorld.csproj]
C:\Users\harry\Source\neo\official\examples\csharp\Directory.Build.targets(4,5): error MSB3073: The command "dotnet C:\Users\harry\Source\neo\official\devpack-dotnet_master-3.x\src\Neo.Compiler.MSIL\bin\Debug\netcoreapp2.0\publish\neon.dll HelloWorld.dll" exited with code -1. [C:\Users\harry\Source\neo\official\examples\csharp\HelloWorld\HelloWorld.csproj]
    0 Warning(s)
    2 Error(s)
```

**Comment by devhawk** [comment]
Quick check in the debugger, ModuleConverter.TryInsertMethod is receiving a null Cecil MethodDefinition instance. ModuleConverter._ConvertCall is failing to resolve the method reference to Neo.SmartContract.Framework.Services.Neo.Storage::Put, but the resolve call is inside a try/catch block that swallows the exception, leading to the null ref exception down the line in TryInsertMethod

**Comment by lightszero** [comment]
I make some test.I think it is not a bug.

When we build "dotnet framework" project, the depend dll like Neo.SmartContract.Framework.dll  will be copy to same path.
but build "dotnet standard" project,will not copy that file


when we build a "dotnet framework" project we will got

> HelloWorld.dll
> HelloWorld.pdb
> Neo.SmartContract.Framework.dll

3 files 


when we build a "dotnet standard" project we will got
> HelloWorld.dll
> HelloWorld.pdb

2 files

**Comment by lightszero** [comment]
I will try to make a better error info in this situation.

**Comment by devhawk** [comment]
Nice to know it's a simple issue. However, instead of forcing the developer to copy the dependency, can we check the nuget global package folder first? https://docs.microsoft.com/en-us/nuget/Consume-Packages/managing-the-global-packages-and-cache-folders

**Comment by lightszero** [comment]
@devhawk 
use “dotnet publish” for netstandard

**Comment by devhawk** [comment]
The point here is to make the smart contract build process as natural and familiar to the C# developer as humanly possible.

**Comment by lock9** [comment]
I think that this is working. Can you check @devhawk ? At least I tested with #131  and it worked fine using .net standard. Thanks.

**Comment by devhawk** [comment]
Yes, I was able to compile the hello world contract to NEF from build artifacts alone using master branch of this repo. Can we port this back to master-2.x branch?

**Comment by shargon** [comment]
Which was exactly the change for allow this?

**Comment by lock9** [comment]
@shargon  can we port #131 to 2.x?

**Comment by shargon** [comment]
Yes, I will
