### ISSUE TITLE
NCCS: IOException with invalid directory

### ISSUE THREAD

**Issue by cschuchardt88** [neo-project/neo-devpack-dotnet#797]
NCCS crashes on invalid directory path See the following Exception log. You need to check if the path is valid and/or catch the exception and display a message indicating the problem.

# Exception Log
```
Target PostBuild:
1>  Task "Exec"
1>    dotnet nccs "CallContract.csproj" -o "C:\Users\Chris\Projects\cschuchardt88\neo-examples-csharp\\sc\"
1>      Determining projects to restore...
1>      All projects are up-to-date for restore.
1>    Unhandled exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
1>     ---> System.IO.IOException: The filename, directory name, or volume label syntax is incorrect. : 'C:\Users\Chris\Projects\cschuchardt88\neo-examples-csharp\sc"'
1>       at System.IO.FileSystem.CreateDirectory(String fullPath, Byte[] securityDescriptor)
1>       at System.IO.Directory.CreateDirectory(String path)
1>       at Neo.Compiler.Program.ProcessOutputs(Options options, String folder, CompilationContext context) in /home/runner/work/neo-devpack-dotnet/neo-devpack-dotnet/src/Neo.Compiler.CSharp/Program.cs:line 140
1>       at Neo.Compiler.Program.ProcessCsproj(Options options, String path) in /home/runner/work/neo-devpack-dotnet/neo-devpack-dotnet/src/Neo.Compiler.CSharp/Program.cs:line 119
1>       at Neo.Compiler.Program.Handle(RootCommand command, Options options, String[] paths, InvocationContext context) in /home/runner/work/neo-devpack-dotnet/neo-devpack-dotnet/src/Neo.Compiler.CSharp/Program.cs:line 75
1>       at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
1>       at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
1>       --- End of inner exception stack trace ---
1>       at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
1>       at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
1>       at System.Delegate.DynamicInvokeImpl(Object[] args)
1>       at System.CommandLine.NamingConventionBinder.ModelBindingCommandHandler.InvokeAsync(InvocationContext context)
1>       at System.CommandLine.NamingConventionBinder.ModelBindingCommandHandler.Invoke(InvocationContext context)
1>       at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
1>    --- End of stack trace from previous location ---
1>       at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass17_0.<<UseParseErrorReporting>b__0>d.MoveNext()
1>    --- End of stack trace from previous location ---
1>       at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass12_0.<<UseHelp>b__0>d.MoveNext()
1>    --- End of stack trace from previous location ---
1>       at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass22_0.<<UseVersionOption>b__0>d.MoveNext()
1>    --- End of stack trace from previous location ---
1>       at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass19_0.<<UseTypoCorrections>b__0>d.MoveNext()
1>    --- End of stack trace from previous location ---
1>       at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__18_0>d.MoveNext()
1>    --- End of stack trace from previous location ---
1>       at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass16_0.<<UseParseDirective>b__0>d.MoveNext()
1>    --- End of stack trace from previous location ---
1>       at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<RegisterWithDotnetSuggest>b__5_0>d.MoveNext()
1>    --- End of stack trace from previous location ---
1>       at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass8_0.<<UseExceptionHandler>b__0>d.MoveNext()
1>    C:\Users\Chris\Projects\cschuchardt88\neo-examples-csharp\src\CallContract\CallContract.csproj(9,5): error MSB3073: The command "dotnet nccs "CallContract.csproj" -o "C:\Users\Chris\Projects\cschuchardt88\neo-examples-csharp\\sc\"" exited with code 1.
1>  Done executing task "Exec" -- FAILED.
```

**Comment by shargon** [comment]
> The filename, directory name, or volume label syntax is incorrect.

With an invalid directory you receive the right message

**Comment by cschuchardt88** [comment]
Its unhandled no? Or is that `dotnet` throwing it?

**Comment by shargon** [comment]
@cschuchardt88 please check #807
